name: Continuous Integration

on: pull_request

jobs:
  continuous-integration:  
    runs-on: ubunto-latest

    steps:
      - uses: action/checkout@v3
      - name: Using Node.js
        uses: actions/setup-node@v2
        with:
            node-version: 20.
      - name: run install, build and test
        run: |
          npm install
          npm build
          npm run test